# Generated by Django 4.2.4 on 2023-08-22 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="veiculo",
            old_name="modelo",
            new_name="modelor",
        ),
    ]
