# Generated by Django 4.2.4 on 2023-08-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("garagem", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="imagem",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="uploader.image"
            ),
        ),
    ]
