# Generated by Django 4.2.4 on 2023-08-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0003_rename_modelor_veiculo_modelo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marca",
            name="nome",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
