# Generated by Django 4.1.7 on 2023-03-31 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0004_alter_cor_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acessório',
            new_name='Acessorio',
        ),
        migrations.RenameModel(
            old_name='Veículo',
            new_name='Veiculo',
        ),
        migrations.AlterModelOptions(
            name='acessorio',
            options={'verbose_name_plural': 'Acessórios'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name_plural': 'Veículos'},
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='acessórios',
            new_name='acessorios',
        ),
    ]
