# Generated by Django 4.2.4 on 2023-08-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0004_alter_marca_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="veiculo",
            name="descricao",
            field=models.CharField(
                blank=True, default="Sem descrição", max_length=300, null=True
            ),
        ),
    ]
